/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Ventanas;

import Admon.Control;
import com.mysql.jdbc.MysqlDataTruncation;
import com.mysql.jdbc.exceptions.MySQLIntegrityConstraintViolationException;
import com.mysql.jdbc.exceptions.MySQLSyntaxErrorException;
import java.awt.event.ActionEvent;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.SQLIntegrityConstraintViolationException;
import javax.swing.JOptionPane;

/**
 *
 * @author Jaime Andres
 */
public class AgregarNuevo extends javax.swing.JFrame {

    /**
     * Creates new form AgregarNuevo
     */
    public AgregarNuevo() {
        initComponents();
   TXTNUMCONTROL.setEnabled(false);     
   TXTNUMCONTROL.setEnabled(false);
   TXTESCUELAPROCEDE.setEnabled(false);
   
   
        
       
        
    }
      

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        TXTNUMEXT = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        TXTPOBLACION = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        TXTPAIS = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        TXTFECHANAC = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        TXTCURP = new javax.swing.JTextField();
        TXTNOMBRE = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        TXTAPELLIDOS = new javax.swing.JTextField();
        TXTCALLE = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        TXTNUMCONTROL = new javax.swing.JTextField();
        TXTESCUELAPROCEDE = new javax.swing.JTextField();
        CBALUMNO = new javax.swing.JCheckBox();
        jLabel13 = new javax.swing.JLabel();
        BTNAGREGAR = new javax.swing.JButton();
        BTNBACK = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        TXTNUMEXT.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                TXTNUMEXTKeyTyped(evt);
            }
        });

        jLabel2.setText("NOMBRE:");

        TXTPOBLACION.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                TXTPOBLACIONKeyTyped(evt);
            }
        });

        jLabel3.setText("APELLIDOS:");

        TXTPAIS.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                TXTPAISKeyTyped(evt);
            }
        });

        jLabel4.setText("CALLE");

        TXTFECHANAC.setText("AAAA-MM-DD");
        TXTFECHANAC.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                TXTFECHANACKeyTyped(evt);
            }
        });

        jLabel5.setText("NUM.EXT");

        TXTNOMBRE.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                TXTNOMBREKeyTyped(evt);
            }
        });

        jLabel1.setText("(año-mes-dia)");

        TXTAPELLIDOS.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                TXTAPELLIDOSKeyTyped(evt);
            }
        });

        TXTCALLE.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                TXTCALLEKeyTyped(evt);
            }
        });

        jLabel7.setText("POBLACION:");

        jLabel8.setText("PAIS:");

        jLabel9.setText("FECHA.NAC");

        jLabel10.setText("CURP");

        jLabel6.setText("NUM-CONTROL:");

        jLabel11.setText("ESCUELA PROCEDENTE:");

        TXTNUMCONTROL.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                TXTNUMCONTROLKeyTyped(evt);
            }
        });

        TXTESCUELAPROCEDE.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                TXTESCUELAPROCEDEKeyTyped(evt);
            }
        });

        CBALUMNO.setText("Alumno");
        CBALUMNO.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CBALUMNOActionPerformed(evt);
            }
        });

        jLabel13.setText("(SI PRETENDE AGREGAR UN ALUMNO HABILITE ESTA CASILLA)");

        BTNAGREGAR.setText("AGREGAR");
        BTNAGREGAR.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BTNAGREGARActionPerformed(evt);
            }
        });

        BTNBACK.setText("REGRESAR");
        BTNBACK.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BTNBACKActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(45, 45, 45)
                        .addComponent(CBALUMNO)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel13))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(29, 29, 29)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel4)
                                    .addComponent(jLabel3)
                                    .addComponent(jLabel2))
                                .addGap(28, 28, 28)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(TXTNOMBRE)
                                    .addComponent(TXTAPELLIDOS)
                                    .addComponent(TXTCALLE, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel10)
                                    .addComponent(jLabel7)
                                    .addComponent(jLabel5)
                                    .addComponent(jLabel8)
                                    .addComponent(jLabel9))
                                .addGap(28, 28, 28)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(TXTNUMEXT)
                                    .addComponent(TXTPOBLACION)
                                    .addComponent(TXTPAIS)
                                    .addComponent(TXTFECHANAC, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(TXTCURP, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel1)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(52, 52, 52)
                        .addComponent(BTNAGREGAR))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(BTNBACK)
                        .addGroup(layout.createSequentialGroup()
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(jLabel11)
                                .addComponent(jLabel6))
                            .addGap(28, 28, 28)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(TXTNUMCONTROL, javax.swing.GroupLayout.DEFAULT_SIZE, 139, Short.MAX_VALUE)
                                .addComponent(TXTESCUELAPROCEDE)))))
                .addGap(49, 49, 49))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(41, 41, 41)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(CBALUMNO)
                    .addComponent(jLabel13))
                .addGap(38, 38, 38)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(TXTNOMBRE, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(TXTAPELLIDOS, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(TXTCALLE, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel6)
                            .addComponent(TXTNUMCONTROL, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel11)
                            .addComponent(TXTESCUELAPROCEDE, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(TXTNUMEXT, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(TXTPOBLACION, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(TXTPAIS, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(BTNAGREGAR))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(TXTFECHANAC, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addGap(11, 11, 11)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(TXTCURP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 33, Short.MAX_VALUE)
                .addComponent(BTNBACK)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void CBALUMNOActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CBALUMNOActionPerformed
   if (CBALUMNO.isSelected()==true){
       TXTNUMCONTROL.setEnabled(true);     
   TXTNUMCONTROL.setEnabled(true);
   TXTESCUELAPROCEDE.setEnabled(true);
   
       
   }else{
     TXTNUMCONTROL.setEnabled(false);     
   TXTNUMCONTROL.setEnabled(false);
   TXTESCUELAPROCEDE.setEnabled(false);
    
   }
       
   
   // TODO add your handling code here:
    }//GEN-LAST:event_CBALUMNOActionPerformed

    private void BTNAGREGARActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BTNAGREGARActionPerformed
      int IDp=0;
        try{
            Class.forName("com.mysql.jdbc.Driver");    
            Connection connect= (Connection) DriverManager.getConnection("jdbc:mysql://localhost/proyectou2bd?"+"user=root&password=jaime");
            try{
               
            String agrega="insert into personas values (default, '"+ TXTNOMBRE.getText()+"', '"+ TXTAPELLIDOS.getText()+"', '"+TXTCALLE.getText()+"', "+TXTNUMEXT.getText()+", '"+TXTPOBLACION.getText()+"', '"+TXTPAIS.getText()+"', '"+TXTFECHANAC.getText()+"', '"+TXTCURP.getText()+"' )";
            PreparedStatement ps2;
            ps2= (PreparedStatement) connect.prepareStatement(agrega);
            ps2.execute();
            PreparedStatement ps;
            JOptionPane.showMessageDialog(null, "Agregado Correctamente");
               
            }catch(SQLIntegrityConstraintViolationException e){
               JOptionPane.showMessageDialog(null,"La CURP ha sido registrada anteriormente, introduzca una diferente"); 
            }catch(MysqlDataTruncation er){
                JOptionPane.showMessageDialog(null,"Introduzca bien la fecha");  
                
            }
            try{
            PreparedStatement ps2;
           
            if(CBALUMNO.isSelected()==true){
                
           
            String curp=TXTCURP.getText();
            String busca = "select * from personas WHERE curp='"+ curp+"'";
            
            ps2 = (PreparedStatement) connect.prepareStatement(busca);
            ResultSet rs = ps2.executeQuery();
            rs.next();
            IDp=rs.getInt("idpersona");
            String agrega2="insert alumnos values (default, "+ TXTNUMCONTROL.getText()+", '"+ TXTESCUELAPROCEDE.getText()+"', '"+IDp+"' )";
           
            ps2= (PreparedStatement) connect.prepareStatement(agrega2);
            ps2.execute();
             JOptionPane.showMessageDialog(null, "Agregado Correctamente");
                
                
        }
            }catch(SQLIntegrityConstraintViolationException er){
                System.out.println(er.getMessage());
                JOptionPane.showMessageDialog(null,"El numero de Control ya ha sido dado de alta anteriormente, intruduzca uno nuevo.");
                String c=TXTCURP.getText();
                String consulta="select idpersona from personas where curp='"+c+"'";
                PreparedStatement ps;
                ps= (PreparedStatement)connect.prepareStatement(consulta);
                ResultSet rs= ps.executeQuery();
                    rs.next();
                    int IDpersona=rs.getInt("idpersona");
                    String eliminar= "delete from personas where idpersona="+IDpersona;
                       ps=(PreparedStatement)connect.prepareStatement(eliminar);
                       ps.execute();
                       ps.close();
                       connect.close();
                       
            }
        
        }
        catch(ClassNotFoundException |SQLException ex){
            System.out.println(ex);
            JOptionPane.showMessageDialog(null,"No Deje espacios en blanco");
        }
      
    }//GEN-LAST:event_BTNAGREGARActionPerformed

    private void BTNBACKActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BTNBACKActionPerformed
Control obj= new Control();
        obj.setVisible(true);
        obj.setLocationRelativeTo(null);
        dispose();        // TODO add your handling code here:
    }//GEN-LAST:event_BTNBACKActionPerformed

    private void TXTNOMBREKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_TXTNOMBREKeyTyped

char c= evt.getKeyChar();
if ((c<'a'|| c>'z')&& (c<' '||c>' ')&& (c<'A'||c>'Z'))evt.consume();
        // TODO add your handling code here:
    }//GEN-LAST:event_TXTNOMBREKeyTyped

    private void TXTAPELLIDOSKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_TXTAPELLIDOSKeyTyped
char c= evt.getKeyChar();
if ((c<'a'|| c>'z')&& (c<' '||c>' ')&& (c<'A'||c>'Z'))evt.consume();      // TODO add your handling code here:
    }//GEN-LAST:event_TXTAPELLIDOSKeyTyped

    private void TXTCALLEKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_TXTCALLEKeyTyped
char c= evt.getKeyChar();
if ((c<'a'|| c>'z')&& (c<' '||c>' ')&& (c<'A'||c>'Z'))evt.consume();        // TODO add your handling code here:
    }//GEN-LAST:event_TXTCALLEKeyTyped

    private void TXTNUMEXTKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_TXTNUMEXTKeyTyped
char c= evt.getKeyChar();
if (c<'0'|| c>'9')evt.consume();        // TODO add your handling code here:
    }//GEN-LAST:event_TXTNUMEXTKeyTyped

    private void TXTPOBLACIONKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_TXTPOBLACIONKeyTyped
char c= evt.getKeyChar();
if ((c<'a'|| c>'z')&& (c<' '||c>' ')&& (c<'A'||c>'Z'))evt.consume();      // TODO add your handling code here:
    }//GEN-LAST:event_TXTPOBLACIONKeyTyped

    private void TXTPAISKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_TXTPAISKeyTyped
char c= evt.getKeyChar();
if ((c<'a'|| c>'z')&& (c<' '||c>' ')&& (c<'A'||c>'Z'))evt.consume();      // TODO add your handling code here:
    }//GEN-LAST:event_TXTPAISKeyTyped

    private void TXTFECHANACKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_TXTFECHANACKeyTyped
char c= evt.getKeyChar();
 if((c<'0' || c>'9') && (c<'-' || c>'/')) evt.consume();        // TODO add your handling code here:
    }//GEN-LAST:event_TXTFECHANACKeyTyped

    private void TXTNUMCONTROLKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_TXTNUMCONTROLKeyTyped
char c= evt.getKeyChar();
if (c<'0'|| c>'9')evt.consume();        // TODO add your handling code here:
    }//GEN-LAST:event_TXTNUMCONTROLKeyTyped

    private void TXTESCUELAPROCEDEKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_TXTESCUELAPROCEDEKeyTyped
char c= evt.getKeyChar();
if ((c<'a'|| c>'z')&& (c<' '||c>' ')&& (c<'A'||c>'Z'))evt.consume();       // TODO add your handling code here:
    }//GEN-LAST:event_TXTESCUELAPROCEDEKeyTyped

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AgregarNuevo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AgregarNuevo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AgregarNuevo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AgregarNuevo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AgregarNuevo().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BTNAGREGAR;
    private javax.swing.JButton BTNBACK;
    private javax.swing.JCheckBox CBALUMNO;
    private javax.swing.JTextField TXTAPELLIDOS;
    private javax.swing.JTextField TXTCALLE;
    private javax.swing.JTextField TXTCURP;
    private javax.swing.JTextField TXTESCUELAPROCEDE;
    private javax.swing.JTextField TXTFECHANAC;
    private javax.swing.JTextField TXTNOMBRE;
    private javax.swing.JTextField TXTNUMCONTROL;
    private javax.swing.JTextField TXTNUMEXT;
    private javax.swing.JTextField TXTPAIS;
    private javax.swing.JTextField TXTPOBLACION;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    // End of variables declaration//GEN-END:variables
}
